//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SABPdf.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SABPdf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   This file is already registered.
        ///Do you want to overwrite the selected content? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgAlreadyRegistered {
            get {
                return ResourceManager.GetString("msgAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)共通設定ファイルで設定していない項目があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgCommonSettingError {
            get {
                return ResourceManager.GetString("msgCommonSettingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)共通設定ファイルがありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgCommonSettingNothing {
            get {
                return ResourceManager.GetString("msgCommonSettingNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirmation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgConfirmation {
            get {
                return ResourceManager.GetString("msgConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)標準機密区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgDefaultSecure {
            get {
                return ResourceManager.GetString("msgDefaultSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please install Acrobat Reader to display the preview.
        ///Or change the default PDF viewer. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgErrAcrobatReader {
            get {
                return ResourceManager.GetString("msgErrAcrobatReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to acquire file information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedFileInformation {
            get {
                return ResourceManager.GetString("msgFailedFileInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to open GCP secrecy documents list (SA secrecy). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedOpenGCPdocument {
            get {
                return ResourceManager.GetString("msgFailedOpenGCPdocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to write PDF user setting file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedPDFUserSettingWrite {
            get {
                return ResourceManager.GetString("msgFailedPDFUserSettingWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to write confidential information of open PDF.
        ///Please save it in Another name or another folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedPDFwrite {
            get {
                return ResourceManager.GetString("msgFailedPDFwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confidential stamp Failed to write paseted PDF.
        ///Please save it in another name or another folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedPDFwritePaste {
            get {
                return ResourceManager.GetString("msgFailedPDFwritePaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read common setting file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedReadCommonFile {
            get {
                return ResourceManager.GetString("msgFailedReadCommonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read document path in common setting file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedReadDocumentPath {
            get {
                return ResourceManager.GetString("msgFailedReadDocumentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to read PDF user setting file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedReadPDF {
            get {
                return ResourceManager.GetString("msgFailedReadPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The stamp pasting process failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedStampPaste {
            get {
                return ResourceManager.GetString("msgFailedStampPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to write user setting file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFailedUserSetting {
            get {
                return ResourceManager.GetString("msgFailedUserSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)最終版 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFinal {
            get {
                return ResourceManager.GetString("msgFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)セキュアフォルダリスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgFolderList {
            get {
                return ResourceManager.GetString("msgFolderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)文書のローカルパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgLocalPath {
            get {
                return ResourceManager.GetString("msgLocalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to delete the preview temporary file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgNotDeletePreviewTemporary {
            get {
                return ResourceManager.GetString("msgNotDeletePreviewTemporary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to delete stamp temporary file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgNotDeleteStampTemporary {
            get {
                return ResourceManager.GetString("msgNotDeleteStampTemporary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attribute information update Failed to delete temporary file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgNotDeleteTemporary {
            get {
                return ResourceManager.GetString("msgNotDeleteTemporary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PDF File is not specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgNotPDFPath {
            get {
                return ResourceManager.GetString("msgNotPDFPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   S secret and A secret files cannot be stored in the specified location. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgNotSavePdf {
            get {
                return ResourceManager.GetString("msgNotSavePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The value of the watermark level is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgNotWatermark {
            get {
                return ResourceManager.GetString("msgNotWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)事業所コード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgOfficeCode {
            get {
                return ResourceManager.GetString("msgOfficeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PDF File(*.pdf)|*.pdf に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgPDFfile {
            get {
                return ResourceManager.GetString("msgPDFfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)プレビューテンポラリファイルの削除に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgPreviewDeleteError {
            get {
                return ResourceManager.GetString("msgPreviewDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confidential stamp The same file as the pasted PDF file name exists.
        ///Please save it in another name or another folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgSameFilePDF {
            get {
                return ResourceManager.GetString("msgSameFilePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select the save destination file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgSelectFile {
            get {
                return ResourceManager.GetString("msgSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)文書のサーバーパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgServerPath {
            get {
                return ResourceManager.GetString("msgServerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)言語設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgSettingLanguage {
            get {
                return ResourceManager.GetString("msgSettingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (EN)zip一時解凍先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string msgTempZipPath {
            get {
                return ResourceManager.GetString("msgTempZipPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type A に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TypeA {
            get {
                return ResourceManager.GetString("TypeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type B に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TypeB {
            get {
                return ResourceManager.GetString("TypeB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   None に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TypeElse {
            get {
                return ResourceManager.GetString("TypeElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type S に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TypeS {
            get {
                return ResourceManager.GetString("TypeS", resourceCulture);
            }
        }
    }
}
